title = "Kreis Jugend Einzel Meisterschaft Schach"
baseURL = "https://kjem.ilmenauer-schachverein.de"
defaultContentLanguage = "de"

[module] 
  [[module.imports]]
    path = "github.com/imfing/hextra"
  [[module.imports]]
    path = "github.com/gethinode/mod-flexsearch"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      linkify = true

  [markup.highlight]
    noClasses = false

[languages]
  [languages.de]
    languageName = "German"
    weight = 1
    title = "KJEM Ilm Kreis"
    contentDir = "content/de"

[menu]

  [[menu.main]]
    name = "Anmeldung"
    url = "/anmeldung"
    weight = -200
  
  [[menu.main]]
    name = "Ausschreibung"
    url = "/2025/ausschreibung"
    weight = -200

  [[menu.main]]
    name = "Ilmenauer Open"
    url = "https://open.ilmenauer-schachverein.de"

    weight = -100
  [[menu.main]]
    name = "Datenschutzerklärung"
    pageRef = "/datenschutzerklaerung"
    weight = 3

  [[menu.main]]
    name = "Ilmenauer Schachverein ↗"
    url = "https://ilmenauer-schachverein.de"
    weight = 4
 
  [[menu.main]]
    name = "Search"
    weight = 5
    [menu.main.params]
      type = "search"

  [[menu.main]]
    name = "GitHub"
    weight = 6
    url = "https://github.com/IlmenauerSchachverein/KJEM"
    [menu.main.params]
      icon = "github"

  [[menu.main]]
    name = "Instagram"
    weight = 7
    url = "https://instagram.com/ilmenauer_schachverein"
    [menu.main.params]
      icon = "instagram"

[params]
  disableToc = true

  [params.navbar]
    displayTitle = true
    displayLogo = true

  [params.theme]
    default = "light"

  [params.footer]
    displayCopyright = true
    displayPoweredBy = true

  [params.editURL]
    enable = false
    base = "https://github.com/IlmenauerSchachverein/KJEM"

  [params.page]
    width = "full"
