name: Build & Deploy Hugo Site

on:
  push:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: write  

concurrency:
  group: kjem-deploy
  cancel-in-progress: true

jobs:
  build-deploy:
    name: Build Hugo & Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v6
        with:
          go-version: "stable"

      - uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true

      - name: Install dos2unix
        run: sudo apt-get update && sudo apt-get install -y dos2unix

      - name: Run build script
        run: |
          dos2unix ./build.sh
          chmod +x ./build.sh
          ./build.sh

      - name: Hugo Build
        run: |
          hugo mod tidy
          hugo --gc --minify --enableGitInfo

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
          cname: kjem.ilmenauer-schachverein.de
